sudo: required
services:
  - docker

before_install:
  - docker build -t kasyap/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kasyap/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket-name: "elasticbeanstalk-us-east-2-146726977421"
  bucket-path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

